name: CI

on:
  push:
    branches:
      - master
      - 'v*'
  pull_request: {}
  schedule:
    - cron: '0 3 * * *' # daily, at 3am

jobs:
  test:
    strategy:
      matrix:
        node: ['12', '14', '16']

    name: Tests (Node.js v${{ matrix.node }})
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - run: yarn install --no-lockfile
      - run: yarn lint
      - run: yarn build
      - run: yarn test:coverage --runInBand
      - run: yarn test:ember

  compatibility:
    name: "Tests (Ember.js, ember-try: ${{ matrix.ember-try-scenario }}, Embroider: ${{ matrix.embroider }})"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        embroider: ["true", "false"]
        ember-try-scenario:
          - ember-qunit-4
          - ember-qunit-5
          - ember-lts-3.28

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12

      - run: yarn install --frozen-lockfile
      - run: node_modules/.bin/ember try:one --config-path tests/dummy/config/ember-try.js ${{ matrix.ember-try-scenario}}
        env:
          USE_EMBROIDER: "${{ matrix.embroider }}"
