name: Release

on:
  push:
    tags:
      - 'v*'

env:
  PNPM_VERSION: 8.8.0

jobs:
  release:
    name: release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.6.0
      - uses: pnpm/action-setup@v2.4.0
        with:
          version: ${{ env.PNPM_VERSION }}

      - uses: actions/setup-node@v3.8.1
        with:
          node-version: 18.17
          registry-url: 'https://registry.npmjs.org'
          cache: pnpm

      - run: pnpm install
      - run: pnpm build

      - name: auto-dist-tag
        run: npx auto-dist-tag@1 --write
        working-directory: packages/qunit-dom

      - run: npm publish
        working-directory: packages/qunit-dom
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
